### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by Aoi-hosizora** [Aoi-hosizora/manhuagui_flutter#21]
This issue contains messages (norifications, new versions) used by manhuagui_api and this android client.

**Comment by Aoi-hosizora** [comment]
```yaml
title: 首条通知公告
notification:
    content: |-
        这是本应用（Manhuagui）的首条通知公告，注意这些通知公告均只来自本应用，并非由漫画柜官方发布。
        针对本应用，今后若有一些 BUG 修复等通知、或有新版本更新等，均会第一时间在此处发布。
        本应用的客户端完全开源，仅供项目学习或日常使用，请勿用于任何商业目的。
    dismissible: true
    link: https://github.com/Aoi-hosizora/manhuagui_flutter
```

**Comment by Aoi-hosizora** [comment]
```yaml
title: 新版本更新
new_version:
    version: 1.2.1
    must_upgrade: false
    release_page: https://github.com/Aoi-hosizora/manhuagui_flutter/releases/tag/v1.2.1
    change_logs: |-
		# 更新日志
		
		添加一些功能，修复一些 BUG，优化用户体验。
		
		### 新功能
		
		+ 提供一些高级设置，以及记录调试日志、清除图像缓存等功能
		+ 添加漫画柜登录签到功能
		+ 添加章节页面图片加载超时功能
		+ 添加消息通知、新版本更新推送功能
		
		### 修复的 BUG
		
		+ 修复 Android 11 及以上版本系统的漫画阅读功能、以及下载保存功能
		+ 修复在屏幕显示较大时一些页面布局错乱的问题
		+ 修复在应用左侧菜单以及章节阅读页中页面跳转的动画细节
		+ 修复漫画评论楼层消失、章节阅读页的页面提示以及页面跳转的错误
		+ 修复其他已知问题
    
```

**Comment by Aoi-hosizora** [comment]
```yaml
title: 新版本更新
new_version:
    version: v1.2.2
    must_upgrade: false
    release_page: https://github.com/Aoi-hosizora/manhuagui_flutter/releases/tag/v1.2.2
    change_logs: |-
        添加一些功能，优化用户体验。

        该版本新增已下载漫画的离线阅读功能，并提供更丰富的主页推荐页面。
```
